export const PORTAL_CHAT_MAX_UPLOAD_BYTES = 300 * 1024
export const PORTAL_CHAT_MAX_IMAGE_BYTES = PORTAL_CHAT_MAX_UPLOAD_BYTES
export const PORTAL_CHAT_MAX_AUDIO_BYTES = PORTAL_CHAT_MAX_UPLOAD_BYTES
export const PORTAL_CHAT_MAX_DOCUMENT_BYTES = PORTAL_CHAT_MAX_UPLOAD_BYTES
export const PORTAL_CHAT_MAX_RECORDING_SECONDS = 18
export const PORTAL_CHAT_AUDIO_BITS_PER_SECOND = 24_000
export const PORTAL_CHAT_MAX_IMAGE_DIMENSION = 1280

export function formatPortalUploadLimit(limitBytes = PORTAL_CHAT_MAX_UPLOAD_BYTES) {
  return `${Math.round(limitBytes / 102.4) / 10}KB`
}
