export const sampleCourses = [
  {
    id: '1',
    title: 'مبانی تجارت ارز',
    description: 'آموزش کامل مبانی تجارت ارز و بازارهای مالی',
    instructor: 'استاد احمد رضایی',
    duration: '8 هفته',
    level: 'مبتدی',
    price: 150000,
    image: '/placeholder-course.jpg',
    category: 'تجارت ارز',
    lessons: 24,
    students: 156,
    rating: 4.8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '2',
    title: 'تحلیل تکنیکال بازارهای مالی',
    description: 'یادگیری تحلیل تکنیکال و استراتژی‌های معاملاتی',
    instructor: 'دکتر فاطمه احمدی',
    duration: '12 هفته',
    level: 'متوسط',
    price: 250000,
    image: '/placeholder-course.jpg',
    category: 'تحلیل تکنیکال',
    lessons: 36,
    students: 89,
    rating: 4.9,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '3',
    title: 'مدیریت ریسک در معاملات',
    description: 'آموزش مدیریت ریسک و حفاظت از سرمایه',
    instructor: 'مهندس علی محمدی',
    duration: '6 هفته',
    level: 'پیشرفته',
    price: 200000,
    image: '/placeholder-course.jpg',
    category: 'مدیریت ریسک',
    lessons: 18,
    students: 67,
    rating: 4.7,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '4',
    title: 'ارزهای دیجیتال و بلاک چین',
    description: 'آشنایی با ارزهای دیجیتال و فناوری بلاک چین',
    instructor: 'دکتر محمد حسینی',
    duration: '10 هفته',
    level: 'مبتدی',
    price: 180000,
    image: '/placeholder-course.jpg',
    category: 'ارز دیجیتال',
    lessons: 30,
    students: 234,
    rating: 4.6,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]

export const sampleTechNews = [
  {
    id: '1',
    title: 'تحولات جدید در بازار ارزهای دیجیتال',
    summary: 'بررسی آخرین تغییرات و نوآوری‌های بازار کریپتو',
    content: 'بازار ارزهای دیجیتال در هفته‌های اخیر شاهد تحولات مهمی بوده است...',
    author: 'تیم تحلیل بازار',
    publishedAt: new Date(),
    category: 'ارز دیجیتال',
    tags: ['بیت کوین', 'اتریوم', 'بازار'],
    imageUrl: '/placeholder-news.jpg',
    source: 'سرای شهزاده',
    isActive: true
  },
  {
    id: '2',
    title: 'نرخ ارز و تأثیر آن بر اقتصاد',
    summary: 'تحلیل تأثیرات نوسانات نرخ ارز بر بازارهای مالی',
    content: 'نوسانات نرخ ارز یکی از مهم‌ترین عوامل تأثیرگذار بر اقتصاد کشور است...',
    author: 'کارشناسان اقتصادی',
    publishedAt: new Date(),
    category: 'اقتصاد',
    tags: ['نرخ ارز', 'اقتصاد', 'تحلیل'],
    imageUrl: '/placeholder-news.jpg',
    source: 'سرای شهزاده',
    isActive: true
  },
  {
    id: '3',
    title: 'راهنمای کامل حواله و انتقال پول',
    summary: 'آموزش کامل نحوه استفاده از سیستم حواله',
    content: 'سیستم حواله یکی از قدیمی‌ترین و مطمئن‌ترین روش‌های انتقال پول است...',
    author: 'متخصصان مالی',
    publishedAt: new Date(),
    category: 'حواله',
    tags: ['حواله', 'انتقال پول', 'راهنما'],
    imageUrl: '/placeholder-news.jpg',
    source: 'سرای شهزاده',
    isActive: true
  },
  {
    id: '4',
    title: 'تحلیل بازار طلا و فلزات گرانبها',
    summary: 'بررسی روند قیمت طلا و پیش‌بینی آینده بازار',
    content: 'بازار طلا و فلزات گرانبها همواره یکی از بازارهای مهم سرمایه‌گذاری بوده است...',
    author: 'تحلیلگران بازار',
    publishedAt: new Date(),
    category: 'طلا و جواهر',
    tags: ['طلا', 'فلزات گرانبها', 'سرمایه‌گذاری'],
    imageUrl: '/placeholder-news.jpg',
    source: 'سرای شهزاده',
    isActive: true
  },
  {
    id: '5',
    title: 'استراتژی‌های موفق در تجارت ارز',
    summary: 'معرفی بهترین استراتژی‌ها برای موفقیت در بازار ارز',
    content: 'موفقیت در بازار ارز نیازمند داشتن استراتژی مناسب و مدیریت ریسک است...',
    author: 'معاملگران حرفه‌ای',
    publishedAt: new Date(),
    category: 'تجارت ارز',
    tags: ['استراتژی', 'تجارت', 'موفقیت'],
    imageUrl: '/placeholder-news.jpg',
    source: 'سرای شهزاده',
    isActive: true
  },
  {
    id: '6',
    title: 'آینده فناوری‌های مالی در افغانستان',
    summary: 'بررسی چشم‌انداز توسعه فین‌تک در کشور',
    content: 'فناوری‌های مالی نوین می‌توانند نقش مهمی در توسعه اقتصادی کشور ایفا کنند...',
    author: 'کارشناسان فناوری',
    publishedAt: new Date(),
    category: 'فناوری مالی',
    tags: ['فین‌تک', 'نوآوری', 'آینده'],
    imageUrl: '/placeholder-news.jpg',
    source: 'سرای شهزاده',
    isActive: true
  }
]